### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by NinesChaosu** [S1nScripts/s1n_npcplacer#1]
Items duplicate when there are more than a few players in the hands of an npc

**Comment by s1nyx** [comment]
Hi @NinesChaosu,

Could you send your config.lua please in order for me to reproduce and fix the problem?

Have a nice day.

**Comment by NinesChaosu** [comment]
`--[[
    Need help with the script ? Go into the Discord support server  https://discord.gg/aKF3DX8yPx
]]

Config = {
    npcs = {
        --[[
            Template:
            {
                position = vector4(x, y, z, heading), -- NPC position X, Y, Z, Heading
                model = "modelName", -- NPC model (here is a list of all models https://wiki.rage.mp/index.php?title=Peds)
                animation = { -- Animation list : https://alexguirre.github.io/animations-list/ (dict in bold, animation name in regular)
                    enable = true, -- Activate the animation for the NPC
                    dict = "dictName", -- Dictionary associated to the animation
                    name = "animationName" -- Animation's name
                },
                props = {
                    enable = true, -- Activate the use of a prop for the NPC
                    list = {
                        {
                            model = "propName", -- Model of the prop
                            position = vec3(x, y, z), -- Position of the prop relative to the NPC
                            rotation = vec3(x, y, z) -- Rotation of the prop relative to the NPC
                        },
                    }
                }
            },
        --]]
        
		-- [Comedy Club NPC] --
		{
            position = vector4(-452.9273, 277.1244, 78.0280, 180.0), -- NPC position X, Y, Z, Heading
            model = "a_m_y_vinewood_02", -- NPC model (here is a list of all models https://wiki.rage.mp/index.php?title=Peds)
            animation = { -- Animation list : https://alexguirre.github.io/animations-list/ (dict in bold, animation name in regular)
                enable = true, -- Activate the animation for the NPC
                dict = "amb@prop_human_seat_chair@male@generic@base", -- Dictionary associated to the animation
                name = "base" -- Animation's name
            },
            props = {
                enable = false, -- Activate the use of a prop for the NPC
                list = {
                    {
                        model = "nil", -- Model of the prop
                        position = vec3(0.00, 0.0, 0.0), -- Position of the prop relative to the NPC
                        rotation = vec3(0.0, 0.0, 0.0) -- Rotation of the prop relative to the NPC
                    },
                }
            }
        },       
		{
            position = vector4(-451.9864, 277.0243, 78.0280, 180.0), -- NPC position X, Y, Z, Heading
            model = "a_f_y_vinewood_01", -- NPC model (here is a list of all models https://wiki.rage.mp/index.php?title=Peds)
            animation = { -- Animation list : https://alexguirre.github.io/animations-list/ (dict in bold, animation name in regular)
                enable = true, -- Activate the animation for the NPC
                dict = "amb@prop_human_seat_chair@female@legs_crossed@base", -- Dictionary associated to the animation
                name = "base" -- Animation's name
            },
            props = {
                enable = false, -- Activate the use of a prop for the NPC
                list = {
                    {
                        model = "nil", -- Model of the prop
                        position = vec3(0.00, 0.0, 0.0), -- Position of the prop relative to the NPC
                        rotation = vec3(0.0, 0.0, 0.0) -- Rotation of the prop relative to the NPC
                    },
                }
            }
        },
		{
            position = vector4(-455.51988, 279.1364, 78.0280, 180.0), -- NPC position X, Y, Z, Heading
            model = "a_m_y_vinewood_04", -- NPC model (here is a list of all models https://wiki.rage.mp/index.php?title=Peds)
            animation = { -- Animation list : https://alexguirre.github.io/animations-list/ (dict in bold, animation name in regular)
                enable = true, -- Activate the animation for the NPC
                dict = "amb@prop_human_seat_chair@male@generic_skinny@base", -- Dictionary associated to the animation
                name = "base" -- Animation's name
            },
            props = {
                enable = false, -- Activate the use of a prop for the NPC
                list = {
                    {
                        model = "nil", -- Model of the prop
                        position = vec3(0.00, 0.0, 0.0), -- Position of the prop relative to the NPC
                        rotation = vec3(0.0, 0.0, 0.0) -- Rotation of the prop relative to the NPC
                    },
                }
            }
        },
		{
            position = vector4(-453.4979, 280.6678, 78.0280, 180.0), -- NPC position X, Y, Z, Heading
            model = "a_f_y_vinewood_02", -- NPC model (here is a list of all models https://wiki.rage.mp/index.php?title=Peds)
            animation = { -- Animation list : https://alexguirre.github.io/animations-list/ (dict in bold, animation name in regular)
                enable = true, -- Activate the animation for the NPC
                dict = "amb@prop_human_seat_chair@female@legs_crossed@base", -- Dictionary associated to the animation
                name = "base" -- Animation's name
            },
            props = {
                enable = false, -- Activate the use of a prop for the NPC
                list = {
                    {
                        model = "nil", -- Model of the prop
                        position = vec3(0.00, 0.0, 0.0), -- Position of the prop relative to the NPC
                        rotation = vec3(0.0, 0.0, 0.0) -- Rotation of the prop relative to the NPC
                    },
                }
            }
        },
		{
            position = vector4(-451.9655, 283.8290, 78.3415, 270), -- NPC position X, Y, Z, Heading
            model = "a_f_y_vinewood_03", -- NPC model (here is a list of all models https://wiki.rage.mp/index.php?title=Peds)
            animation = { -- Animation list : https://alexguirre.github.io/animations-list/ (dict in bold, animation name in regular)
                enable = true, -- Activate the animation for the NPC
                dict = "amb@prop_human_seat_chair@female@proper_skinny@base", -- Dictionary associated to the animation
                name = "base" -- Animation's name
            },
            props = {
                enable = false, -- Activate the use of a prop for the NPC
                list = {
                    {
                        model = "nil", -- Model of the prop
                        position = vec3(0.00, 0.0, 0.0), -- Position of the prop relative to the NPC
                        rotation = vec3(0.0, 0.0, 0.0) -- Rotation of the prop relative to the NPC
                    },
                }
            }
        },
		{
            position = vector4(-450.6054, 283.2381, 78.5215, 90.0), -- NPC position X, Y, Z, Heading
            model = "s_f_y_clubbar_01", -- NPC model (here is a list of all models https://wiki.rage.mp/index.php?title=Peds)
            animation = { -- Animation list : https://alexguirre.github.io/animations-list/ (dict in bold, animation name in regular)
                enable = true, -- Activate the animation for the NPC
                dict = "amb@world_human_hang_out_street@female_arms_crossed@idle_a", -- Dictionary associated to the animation
                name = "idle_a" -- Animation's name
            },
            props = {
                enable = false, -- Activate the use of a prop for the NPC
                list = {
                    {
                        model = "nil", -- Model of the prop
                        position = vec3(0.00, 0.0, 0.0), -- Position of the prop relative to the NPC
                        rotation = vec3(0.0, 0.0, 0.0) -- Rotation of the prop relative to the NPC
                    },
                }
            }
        },
		{
            position = vector4(-454.5185, 286.8637, 78.5215, 180.0), -- NPC position X, Y, Z, Heading
            model = "a_m_y_vinewood_01", -- NPC model (here is a list of all models https://wiki.rage.mp/index.php?title=Peds)
            animation = { -- Animation list : https://alexguirre.github.io/animations-list/ (dict in bold, animation name in regular)
                enable = true, -- Activate the animation for the NPC
                dict = "amb@world_human_leaning@female@wall@back@hand_up@idle_a", -- Dictionary associated to the animation
                name = "idle_a" -- Animation's name
            },
            props = {
                enable = false, -- Activate the use of a prop for the NPC
                list = {
                    {
                        model = "nil", -- Model of the prop
                        position = vec3(0.00, 0.0, 0.0), -- Position of the prop relative to the NPC
                        rotation = vec3(0.0, 0.0, 0.0) -- Rotation of the prop relative to the NPC
                    },
                }
            }
        },
		-- [Church NPC] --	
		{
            position = vector4(-536.9749, -217.8281, 37.6497, 30.0), -- NPC position X, Y, Z, Heading
            model = "player_two", -- NPC model (here is a list of all models https://wiki.rage.mp/index.php?title=Peds)
            animation = { -- Animation list : https://alexguirre.github.io/animations-list/ (dict in bold, animation name in regular)
                enable = true, -- Activate the animation for the NPC
                dict = "mp_player_intdrink", -- Dictionary associated to the animation
                name = "loop_bottle" -- Animation's name
            },
            props = {
                enable = true, -- Activate the use of a prop for the NPC
                list = {
                    {
                        model = "prop_amb_beer_bottle", -- Model of the prop
                        position = vec3(0.01, 0.01, 0.01), -- Position of the prop relative to the NPC
                        rotation = vec3(0.0, 0.0, -1.5) -- Rotation of the prop relative to the NPC
                    },
                }
            }
        },		
    }
}`
